namespace SilentStream.Core.Contracts;

/// <summary>
/// Retrieves an authorized channel's YouTube caption track as an in-memory SRT file.
/// </summary>
public interface IYouTubeCaptionService
{
    /// <summary>
    /// Downloads the preferred caption track for <paramref name="videoId"/> as SRT.
    /// Chooses an exact or primary-language match for <paramref name="preferredLanguage"/>,
    /// then Korean, then the first available track. Returns <see langword="null"/> when the
    /// video has no downloadable caption tracks; authorization and API errors propagate to the
    /// caller.
    /// </summary>
    Task<CaptionDownload?> DownloadPreferredSrtAsync(
        string videoId,
        string? preferredLanguage,
        CancellationToken ct);
}

/// <summary>
/// An SRT caption track retrieved from YouTube. <see cref="Srt"/> is held only in memory;
/// persistence and response authorization are responsibilities of the caller.
/// </summary>
/// <param name="VideoId">The YouTube video the track belongs to.</param>
/// <param name="CaptionId">The YouTube caption-track identifier.</param>
/// <param name="Language">The selected track's BCP-47 language tag.</param>
/// <param name="Name">The user-visible track name, if present.</param>
/// <param name="IsAutoGenerated">Whether YouTube identifies the track as ASR-generated.</param>
/// <param name="Srt">The downloaded SubRip file bytes.</param>
public sealed record CaptionDownload(
    string VideoId,
    string CaptionId,
    string Language,
    string? Name,
    bool IsAutoGenerated,
    byte[] Srt);
